<?php
use App\Controllers\AuthController;
use App\Controllers\ElectionController;
use App\Controllers\HomeController;
use App\Controllers\PartyListController;
use App\Controllers\CandidateController;
use App\Controllers\PositionController;
use App\Controllers\ReportController;
use App\Controllers\StudentController;
use App\Controllers\VoteController;
use App\Middleware\AuthMiddleware;
use App\Middleware\GuestMiddleware;
use App\Middleware\RoleMiddleware;

$router->get('/login', [AuthController::class, 'loginForm'], [GuestMiddleware::class]);
$router->post('/login', [AuthController::class, 'login'], [GuestMiddleware::class]);
$router->get('/register', [AuthController::class, 'registerForm'], [GuestMiddleware::class]);
$router->post('/register', [AuthController::class, 'register'], [GuestMiddleware::class]);
$router->get('/logout', [AuthController::class, 'logout'], [AuthMiddleware::class]);
$router->get('/', [HomeController::class, 'redirectToDashboard'], [AuthMiddleware::class]);
$router->get('/dashboard', [HomeController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/dashboard/stats', [HomeController::class, 'dashboardStats'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/dashboard/charts/votes-trend', [HomeController::class, 'votesTrend'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/elections', [ElectionController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/elections/create', [ElectionController::class, 'store'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/elections/update', [ElectionController::class, 'update'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/elections/delete', [ElectionController::class, 'delete'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/elections/activate', [ElectionController::class, 'activate'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/elections/deactivate', [ElectionController::class, 'deactivate'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/positions', [PositionController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/positions/create', [PositionController::class, 'store'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/positions/update', [PositionController::class, 'update'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/positions/delete', [PositionController::class, 'delete'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/partylists', [PartyListController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/partylists/create', [PartyListController::class, 'store'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/partylists/update', [PartyListController::class, 'update'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/partylists/delete', [PartyListController::class, 'delete'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/candidates', [CandidateController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/candidates/create', [CandidateController::class, 'store'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/candidates/update', [CandidateController::class, 'update'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/candidates/delete', [CandidateController::class, 'delete'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/students', [StudentController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/students/create', [StudentController::class, 'store'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/students/update', [StudentController::class, 'update'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/students/delete', [StudentController::class, 'delete'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->post('/admin/students/import', [StudentController::class, 'import'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/reports', [ReportController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/reports/data', [ReportController::class, 'data'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/admin/reports/export', [ReportController::class, 'export'], [AuthMiddleware::class, RoleMiddleware::class . ':admin']);
$router->get('/student/dashboard', [HomeController::class, 'studentDashboard'], [AuthMiddleware::class, RoleMiddleware::class . ':student']);
$router->get('/student/vote', [VoteController::class, 'index'], [AuthMiddleware::class, RoleMiddleware::class . ':student']);
$router->post('/student/vote/submit', [VoteController::class, 'submit'], [AuthMiddleware::class, RoleMiddleware::class . ':student']);
$router->get('/student/vote/confirmation', [VoteController::class, 'confirmation'], [AuthMiddleware::class, RoleMiddleware::class . ':student']);
